import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
  display: "swap",
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
  display: "swap",
});

export const metadata = {
  title: "Vinyl Vault",
  description: "Generated by create next app",
  themeColor: [
    { media: "(prefers-color-scheme: light)", color: "#ededed" },
    { media: "(prefers-color-scheme: dark)", color: "#0a0a0a" },
  ],
  appleWebApp: {
    capable: true,
    // 'black' | 'default' | 'black-translucent'
    statusBarStyle: "black-translucent",
  },
};

export const viewport = {
  width: "device-width",
  initialScale: 1,
  viewportFit: "cover", // enable safe-area env() on iOS
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className="h-full">
      <body
        className={[
          geistSans.variable,
          geistMono.variable,
          // mobile-safe full height + match Safari bars to background
          "min-h-[100dvh] bg-background text-foreground antialiased",
          // no horizontal scroll
          "overflow-x-clip",
          // pad under the notch & home indicator on iOS
          "pt-[env(safe-area-inset-top)] pb-[env(safe-area-inset-bottom)]",
        ].join(" ")}
      >
        <div className="max-w-6xl mx-auto px-4 md:px-8 py-4 md:py-8">
          {children}
        </div>
      </body>
    </html>
  );
}
